version: '3'

name: sd

services:
  sensor:
    image: sensor
    build:
      context: ./sensor-simulator
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - LOGGING_CONFIG=10 #DEBUG

  calculator:
    image: calculator
    build:
      context: ./calculator
    container_name: calculator
    environment:
      - LOGGING_CONFIG=20 #INFO

  alarm:
    image: alarm
    build:
      context: ./alarm
    container_name: alarm
    ports:
      - 8001:8080
    environment:
      - LOGGING_CONFIG=20 #INFO
    